CREATE TABLE IF NOT EXISTS teacher
(
    teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    age        INTEGER,
    sex        VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_teacher PRIMARY KEY (teacher_id),
    CONSTRAINT unique_teacher_email UNIQUE (email)
    );
