CREATE TABLE IF NOT EXISTS student
(
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    age        INTEGER,
    sex        VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    teacher_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (student_id),
    CONSTRAINT unique_student_email UNIQUE (email),
    CONSTRAINT TEACHER_ID_FK FOREIGN KEY (teacher_id) REFERENCES teacher (teacher_id) ON DELETE CASCADE
);


